#!/bin/bash
DIR=`dirname "$(readlink -f "$0")"`
[ -d $HOME/.oh-my-zsh ] && rm -rf $HOME/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp -r $DIR/. $HOME
