#!/bin/bash

# This script LOCALLY installs dotfiles

# Link config files
DIR=`dirname "$(readlink -f "$0")"`
for f in .zshrc .vimrc .tmux.conf .aria2; do
 ln -vfs $DIR/$f $HOME
done

# Install or update oh-my-zsh
if [ -d $HOME/.oh-my-zsh ]; then
  pushd $HOME/.oh-my-zsh
  ./tools/upgrade.sh
  popd
else
  KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

