" set the theme
colorscheme monokai

" Make Vim more useful
set nocompatible

" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed

" Enhance command-line completion
set wildmenu

" Allow cursor keys in insert mode
set esckeys

" Allow backspace in insert mode
set backspace=indent,eol,start

" Optimize for fast terminal connections
set ttyfast

" Add the g flag to search/replace by default
set gdefault

" Use UTF-8 without BOM
set encoding=utf-8 nobomb

" Change mapleader
let mapleader=","

" Don't add empty newlines at the end of files
set binary
set noeol

" Respect modeline in files
set modeline
set modelines=4

" Line numbers
set nu

" Enable syntax highlighting
syntax on

" Highlight current line
" set cursorline

" Make tabs as wide as two spaces
set tabstop=4

" Highlight searches
set hlsearch

" Ignore case of searches
set ignorecase

" Highlight dynamically as pattern is typed
set incsearch

" Always show status line
set laststatus=2

" Disable error bells
set noerrorbells

" Don? reset cursor to start of line when moving around.
set nostartofline

" Show the cursor position
set ruler

" Don? show the intro message when starting Vim
set shortmess=atI

" Show the current mode
set showmode

" Show the filename in the window titlebar
set title

" Show the (partial) command as it? being typed
set showcmd

" Set swap and backupdir
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Use relative line numbers
"if exists("&relativenumber")
"	set relativenumber
"	au BufReadPost * set relativenumber
"endif

" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Strip trailing whitespace (,ss)
function! StripWhitespace()
	let save_cursor = getpos(".")
	let old_query = getreg('/')
	:%s/\s\+$//e
	call setpos('.', save_cursor)
	call setreg('/', old_query)
endfunction

noremap <leader>ss :call StripWhitespace()<CR>

" Save a file as root :)
cmap W! w !sudo tee % > /dev/null<CR>:e!<CR><CR> 

" tab navigation like firefox
nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-t>     :tabnew<CR>

" tab navigation like VIM !
nnoremap zgg  :tabfirst<CR>
nnoremap zG  :tablast<CR>

nnoremap zj  :tabnext<CR>
nnoremap zl  :tabnext<CR>

nnoremap zk  :tabprev<CR>
nnoremap zh  :tabprev<CR>

nnoremap zn  :tabnew<CR>
nnoremap zc  :tabnew<CR>

nnoremap zm  :tabclose<CR>
nnoremap zx  :tabclose<CR>

" Remove dos \r
nnoremap dm :%s/\r//g <CR>

" Reload vim config
cnoreabbrev reload :so %<CR>

" Shell
set shell=zsh
